### ISSUE TITLE
Critical Issue :: NPE and one row with no icon and name is shown.

### ISSUE THREAD

**Issue by AnuragSingla911** [gaurav133/PhoneUse#158]
07-10 11:27:36.867 10970 10970 D AndroidRuntime: Shutting down VM
07-10 11:27:36.887 10970 10970 E AndroidRuntime: FATAL EXCEPTION: main
07-10 11:27:36.887 10970 10970 E AndroidRuntime: Process: com.asgj.android.appusage, PID: 10970
07-10 11:27:36.887 10970 10970 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equals(java.lang.Object)' on a null object reference
07-10 11:27:36.887 10970 10970 E AndroidRuntime:    at com.asgj.android.appusage.activities.UsageListMainActivity.onUsageItemClick(UsageListMainActivity.java:889)
07-10 11:27:36.887 10970 10970 E AndroidRuntime:    at com.asgj.android.appusage.activities.UsageListFragment$SamplePagerAdapter.onItemClicked(UsageListFragment.java:665)
07-10 11:27:36.887 10970 10970 E AndroidRuntime:    at com.asgj.android.appusage.ui.widgets.UsageListAdapter.onTouch(UsageListAdapter.java:219)

**Comment by AnuragSingla911** [comment]
once issue. check is applied.. but need to find why
07-10 11:27:26.087 10970 10970 W System.err: android.content.pm.PackageManager$NameNotFoundException
07-10 11:27:26.097 10970 10970 W System.err:    at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:281)
07-10 11:27:26.097 10970 10970 W System.err:    at com.asgj.android.appusage.Utility.Utils.getApplicationLabelName(Utils.java:465) this scenrio appears. applying logs for future testing reference

**Comment by AnuragSingla911** [comment]
issue is not in the case of app uninstall.
need to find the scenrio..
app uninstall case is working fine. ic_launcher and pakage name shows

**Comment by AnuragSingla911** [comment]
not found the reproduction path yet

**Comment by AnuragSingla911** [comment]
not found the path but issue some where exist..
